server:
  port: 8082


spring:
  application:
    name: open-ai

# Eureka config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671//eureka/


#open-ai=Configuration
#openai.model=gpt-3.5-turbo
#openai.api.url=https://api.openai.com/v1/chat/completions
openai:
  api:
    key: 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

